/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Class_File.FILE_IO;
import Class_File.ManagerClass;
import Class_File.SchedulerClass;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author junyong is DaShuaiGe
 */
public class pn_SA_assign extends javax.swing.JPanel {
    private ManagerMainPage managerMainPage;
    private String IssueID;
    private String ManagerID;
    private String HallID;

    /**
     * Creates new form pn_SA_assign
     */
    public pn_SA_assign(ManagerMainPage managerMainPage, String Issue_ID, String managerID, String hallid) throws Exception {
        this.managerMainPage = managerMainPage;
        this.IssueID = Issue_ID;
        this.ManagerID = managerID;
        this.HallID = hallid;
        initComponents();
        
        FILE_IO F = new FILE_IO();
        
        LBL_SA_IssueID.setText(IssueID);
        LBL_SA_HallID.setText(HallID);
        LBL_SA_ManagerID.setText(ManagerID);
        System.out.println("22");
        
        //这个要自动生成id
        LBL_SA_assignmentID.setText(F.getNextAssignmentID());
        System.out.println("22");
        
        try {
            List<SchedulerClass> schedulers = F.getAllScheduler();
            for (SchedulerClass scheduler : schedulers) {
                cbo_SA_assignScheduler.addItem(scheduler.getUserID());
            }
            System.out.println("22");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_SA_assign = new javax.swing.JPanel();
        lbl_Title2 = new javax.swing.JLabel();
        lbl_SA_content4 = new javax.swing.JLabel();
        lbl_SA_content5 = new javax.swing.JLabel();
        btn_SA_cancel = new javax.swing.JButton();
        btn_SA_confirm = new javax.swing.JButton();
        lbl_SA_content7 = new javax.swing.JLabel();
        lbl_SA_content8 = new javax.swing.JLabel();
        lbl_SA_content9 = new javax.swing.JLabel();
        cbo_SA_assignScheduler = new javax.swing.JComboBox<>();
        lbl_SA_content10 = new javax.swing.JLabel();
        cbo_SA_IssueStatus = new javax.swing.JComboBox<>();
        lbl_SA_content11 = new javax.swing.JLabel();
        txt_SA_remark = new javax.swing.JTextField();
        LBL_SA_assignmentID = new javax.swing.JLabel();
        LBL_SA_IssueID = new javax.swing.JLabel();
        LBL_SA_HallID = new javax.swing.JLabel();
        LBL_SA_ManagerID = new javax.swing.JLabel();

        lbl_Title2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title2.setText("Scheduler Assignment");

        lbl_SA_content4.setText("Assignment ID :");

        lbl_SA_content5.setText("Issue ID :");

        btn_SA_cancel.setText("Cancel");
        btn_SA_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_cancelActionPerformed(evt);
            }
        });

        btn_SA_confirm.setText("Confirm");
        btn_SA_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_confirmActionPerformed(evt);
            }
        });

        lbl_SA_content7.setText("Hall ID :");

        lbl_SA_content8.setText("Manager ID : (Auto-filled)");

        lbl_SA_content9.setText("Assign Scheduler :");

        lbl_SA_content10.setText("Issue Status :");

        cbo_SA_IssueStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Done", "Closed", "Cancelled" }));

        lbl_SA_content11.setText("Remark (Optional) :");

        LBL_SA_assignmentID.setText("jLabel1");

        LBL_SA_IssueID.setText("jLabel1");

        LBL_SA_HallID.setText("jLabel1");

        LBL_SA_ManagerID.setText("jLabel1");

        javax.swing.GroupLayout pn_SA_assignLayout = new javax.swing.GroupLayout(pn_SA_assign);
        pn_SA_assign.setLayout(pn_SA_assignLayout);
        pn_SA_assignLayout.setHorizontalGroup(
            pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_assignLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addComponent(lbl_Title2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content4)
                            .addComponent(lbl_SA_content7)
                            .addComponent(LBL_SA_assignmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_SA_HallID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SA_content5)
                            .addComponent(lbl_SA_content8)
                            .addComponent(LBL_SA_IssueID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_SA_ManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_SA_assignLayout.createSequentialGroup()
                        .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_SA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content9)
                            .addComponent(cbo_SA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_SA_content10)
                            .addComponent(lbl_SA_content11)
                            .addComponent(txt_SA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(btn_SA_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btn_SA_confirm)))
                .addGap(340, 340, 340))
        );
        pn_SA_assignLayout.setVerticalGroup(
            pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_assignLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SA_assignLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_SA_assignmentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_SA_content7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_SA_HallID)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_SA_content9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pn_SA_assignLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_SA_IssueID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(lbl_SA_content8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL_SA_ManagerID)
                        .addGap(40, 40, 40)))
                .addComponent(cbo_SA_assignScheduler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lbl_SA_content10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_SA_IssueStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_SA_content11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SA_remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_SA_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SA_cancel)
                    .addComponent(btn_SA_confirm))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_assign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_assign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SA_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_cancelActionPerformed
        try {
            managerMainPage.switchToPage(new pn_SA_home(managerMainPage,ManagerID));
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SA_cancelActionPerformed

    private void btn_SA_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_confirmActionPerformed
        String Assignment_ID = LBL_SA_assignmentID.getText();
        String Issue_ID = LBL_SA_IssueID.getText();
        String Hall_ID = LBL_SA_HallID.getText();
        String Manager_ID = LBL_SA_ManagerID.getText();
        String Scheduler_ID = (String) cbo_SA_assignScheduler.getSelectedItem();
        
        String Assignment_Status = (String) cbo_SA_IssueStatus.getSelectedItem();
        String Remark = txt_SA_remark.getText();
        FILE_IO F = new FILE_IO();
        
        try {
            ManagerClass Manager = F.getManagerByID(Manager_ID);
            Manager.AssignScheduler(Assignment_ID, Issue_ID, Hall_ID, Manager_ID, Scheduler_ID, Assignment_Status, Remark);
            JOptionPane.showMessageDialog(null,"This issue had been assign to a scheduler ");
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SA_confirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_SA_HallID;
    private javax.swing.JLabel LBL_SA_IssueID;
    private javax.swing.JLabel LBL_SA_ManagerID;
    private javax.swing.JLabel LBL_SA_assignmentID;
    private javax.swing.JButton btn_SA_cancel;
    private javax.swing.JButton btn_SA_confirm;
    private javax.swing.JComboBox<String> cbo_SA_IssueStatus;
    private javax.swing.JComboBox<String> cbo_SA_assignScheduler;
    private javax.swing.JLabel lbl_SA_content10;
    private javax.swing.JLabel lbl_SA_content11;
    private javax.swing.JLabel lbl_SA_content4;
    private javax.swing.JLabel lbl_SA_content5;
    private javax.swing.JLabel lbl_SA_content7;
    private javax.swing.JLabel lbl_SA_content8;
    private javax.swing.JLabel lbl_SA_content9;
    private javax.swing.JLabel lbl_Title2;
    private javax.swing.JPanel pn_SA_assign;
    private javax.swing.JTextField txt_SA_remark;
    // End of variables declaration//GEN-END:variables
}
