/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Class_File.FILE_IO;
import Class_File.HandleCustomerFeedback;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyong is DaShuaiGe
 */
public class pn_SA_viewHallMaintenance extends javax.swing.JPanel {
    private ManagerMainPage managerMainPage;
    private String ManagerID;
    /**
     * Creates new form pn_SA_viewHallMaintenance
     */
    public pn_SA_viewHallMaintenance(ManagerMainPage managerMainPage, String managerID) throws IOException {
        this.managerMainPage = managerMainPage;
        this.ManagerID = managerID;
        initComponents();
        
        FILE_IO F = new FILE_IO();
        List<String[]> tableData = F.readDataFromFile();
        
        DefaultTableModel model_Feedback = (DefaultTableModel) tbl_HM_hallMaintenance.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        // 清空现有行
        model_Feedback.setRowCount(0);

        // 将每个 Hall 数据添加到表格中
        for (String[] Data : tableData) {
            Object[] rowData = {
                Data[0],
                Data[1],
                Data[2],
                Data[3],
                Data[4],
                Data[5],
                Data[6],
                Data[7]
            };
            model_Feedback.addRow(rowData);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_SA_viewHallMaintenance = new javax.swing.JPanel();
        lbl_Title4 = new javax.swing.JLabel();
        lbl_SA_content18 = new javax.swing.JLabel();
        cbo_HM_maintenanceStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HM_hallMaintenance = new javax.swing.JTable();
        btn_HM_back = new javax.swing.JButton();

        lbl_Title4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title4.setText("Hall Maintenance");

        lbl_SA_content18.setText("View Maintenance Status :");

        cbo_HM_maintenanceStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Done", "Closed", "Cancelled" }));
        cbo_HM_maintenanceStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_HM_maintenanceStatusActionPerformed(evt);
            }
        });

        tbl_HM_hallMaintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall ID", "Scheduler ID", "Manager ID", "Assigned Date", "Start Date Time", "End Date Time", "Maintenance Status", "Remark"
            }
        ));
        jScrollPane2.setViewportView(tbl_HM_hallMaintenance);

        btn_HM_back.setText("Back");
        btn_HM_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HM_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_SA_viewHallMaintenanceLayout = new javax.swing.GroupLayout(pn_SA_viewHallMaintenance);
        pn_SA_viewHallMaintenance.setLayout(pn_SA_viewHallMaintenanceLayout);
        pn_SA_viewHallMaintenanceLayout.setHorizontalGroup(
            pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addComponent(lbl_SA_content18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_HM_maintenanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_HM_back)
                        .addGap(19, 19, 19))
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addComponent(lbl_Title4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pn_SA_viewHallMaintenanceLayout.setVerticalGroup(
            pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_viewHallMaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title4)
                .addGap(30, 30, 30)
                .addGroup(pn_SA_viewHallMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SA_content18)
                    .addComponent(cbo_HM_maintenanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_HM_back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_viewHallMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_viewHallMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HM_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HM_backActionPerformed
        try {
            managerMainPage.switchToPage(new pn_SA_home(managerMainPage, ManagerID));
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_HM_backActionPerformed

    private void cbo_HM_maintenanceStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_HM_maintenanceStatusActionPerformed
        // Get selected item from combo box
        String selectedFilter = cbo_HM_maintenanceStatus.getSelectedItem().toString();

        // Initialize a new list to store filtered data
        FILE_IO F = new FILE_IO();
        List<String[]> filteredData = new ArrayList<>();
        List<String[]> tableData = null;
        try {
            tableData = F.readDataFromFile();
        } catch (IOException ex) {
            Logger.getLogger(pn_SA_viewHallMaintenance.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Iterate over the original data and filter based on Data[6]
        for (String[] row : tableData) {
            System.out.println(row[6]);
            if (row[6].equalsIgnoreCase(selectedFilter)) {
                System.out.println(row[6]);
                filteredData.add(row); // Add matching rows to the filtered list
            }
        }

        // Clear the existing rows in the table
        DefaultTableModel model_Feedback = (DefaultTableModel) tbl_HM_hallMaintenance.getModel();
        model_Feedback.setRowCount(0); // Clear the table
        
        // Add filtered data to the table
        for (String[] rowData : filteredData) {
            model_Feedback.addRow(rowData); // Populate the table with filtered data
        }
    }//GEN-LAST:event_cbo_HM_maintenanceStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HM_back;
    private javax.swing.JComboBox<String> cbo_HM_maintenanceStatus;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_SA_content18;
    private javax.swing.JLabel lbl_Title4;
    private javax.swing.JPanel pn_SA_viewHallMaintenance;
    private javax.swing.JTable tbl_HM_hallMaintenance;
    // End of variables declaration//GEN-END:variables
}
