/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Class_File.FILE_IO;
import Class_File.HandleCustomerFeedback;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junyong is DaShuaiGe
 */
public class pn_SA_home extends javax.swing.JPanel {
    private ManagerMainPage managerMainPage;
    private String ManagerID;
    
    /**
     * Creates new form pn_SA_home
     */
    public pn_SA_home(ManagerMainPage managerMainPage, String managerID) throws Exception {
        this.managerMainPage = managerMainPage;
        this.ManagerID = managerID;
        initComponents();
        
        FILE_IO F = new FILE_IO();
        
        List<HandleCustomerFeedback> Issues = F.getAllIssue();

        DefaultTableModel model_Feedback = (DefaultTableModel) tbl_SA_schedulerassignment.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        // 清空现有行
        model_Feedback.setRowCount(0);

        // 将每个 Hall 数据添加到表格中
        for (HandleCustomerFeedback Issue : Issues) {
            System.out.println(Issue.getFeedback_ID());
            Object[] rowData = {
                Issue.getFeedback_ID(),
                Issue.getTitle(),
                Issue.getContent(),
                Issue.getIssue_hall().getHall_ID(),
                Issue.getFeedbackDateTime().format(formatter)
            };
            model_Feedback.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_SA_home = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SA_schedulerassignment = new javax.swing.JTable();
        lbl_SA_content3 = new javax.swing.JLabel();
        txt_SA_searchIssueID = new javax.swing.JTextField();
        btn_SA_view = new javax.swing.JButton();
        btn_SA_assign = new javax.swing.JButton();
        btn_SA_update = new javax.swing.JButton();
        btn_SA_viewhallmaintenance = new javax.swing.JButton();

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("Scheduler Assignment");

        tbl_SA_schedulerassignment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Tittle", "Content", "Hall ID", "Feedback Time"
            }
        ));
        jScrollPane1.setViewportView(tbl_SA_schedulerassignment);

        lbl_SA_content3.setText("Quick Search : Enter Issue ID to Search (Eg. I002)");

        txt_SA_searchIssueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SA_searchIssueIDActionPerformed(evt);
            }
        });

        btn_SA_view.setText("View");
        btn_SA_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_viewActionPerformed(evt);
            }
        });

        btn_SA_assign.setText("Assign");
        btn_SA_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_assignActionPerformed(evt);
            }
        });

        btn_SA_update.setText("Update");
        btn_SA_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_updateActionPerformed(evt);
            }
        });

        btn_SA_viewhallmaintenance.setText("View Hall Maintenance");
        btn_SA_viewhallmaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SA_viewhallmaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_SA_homeLayout = new javax.swing.GroupLayout(pn_SA_home);
        pn_SA_home.setLayout(pn_SA_homeLayout);
        pn_SA_homeLayout.setHorizontalGroup(
            pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_homeLayout.createSequentialGroup()
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Title1))
                    .addGroup(pn_SA_homeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_SA_content3)
                                .addGroup(pn_SA_homeLayout.createSequentialGroup()
                                    .addComponent(txt_SA_searchIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_SA_view, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_SA_homeLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btn_SA_viewhallmaintenance)
                                    .addGap(76, 76, 76)
                                    .addComponent(btn_SA_assign)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_SA_update))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        pn_SA_homeLayout.setVerticalGroup(
            pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SA_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addGap(28, 28, 28)
                .addComponent(lbl_SA_content3)
                .addGap(2, 2, 2)
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SA_searchIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SA_view))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_SA_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SA_assign)
                    .addComponent(btn_SA_viewhallmaintenance)
                    .addComponent(btn_SA_update))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_SA_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SA_searchIssueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SA_searchIssueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SA_searchIssueIDActionPerformed

    private void btn_SA_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_viewActionPerformed
        String IssueID = txt_SA_searchIssueID.getText();
        DefaultTableModel model_Feedback = (DefaultTableModel) tbl_SA_schedulerassignment.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        FILE_IO F = new FILE_IO();

        List<HandleCustomerFeedback> Issues = null;
        try {
            Issues = F.getAllIssue();
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_home.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (HandleCustomerFeedback Issue : Issues) {
            if(Issue.getFeedback_ID().equals(IssueID)){
                model_Feedback.setRowCount(0);
                Object[] rowData = {
                    Issue.getFeedback_ID(),
                    Issue.getTitle(),
                    Issue.getContent(),
                    Issue.getIssue_hall().getHall_ID(),
                    Issue.getFeedbackDateTime().format(formatter)
                };
                model_Feedback.addRow(rowData);
            }
        }
    }//GEN-LAST:event_btn_SA_viewActionPerformed

    private void btn_SA_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_assignActionPerformed
        try {
            int selectedRow = tbl_SA_schedulerassignment.getSelectedRow();
                if (selectedRow != -1) {
                    // 获取选中的行数据（假设你要传递整行数据）
                    
                    
                    String data1 = (String) tbl_SA_schedulerassignment.getValueAt(selectedRow, 0);  
                    String data2 = (String) tbl_SA_schedulerassignment.getValueAt(selectedRow, 3);  

                    // 创建新页面，并将数据传递给它
                    System.out.println(ManagerID);
                    System.out.println(data1);
                    System.out.println(data2);
                    pn_SA_assign newPage = new pn_SA_assign(managerMainPage, data1, ManagerID, data2);
                    managerMainPage.switchToPage(newPage);  // 切换到新页面
                } else {
                    // 弹出警告，提醒用户选择一行
                    JOptionPane.showMessageDialog(null, "Please select a row to assign.");
                }
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_SA_assignActionPerformed

    private void btn_SA_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_updateActionPerformed
        try {
                managerMainPage.switchToPage(new pn_SA_update(managerMainPage, ManagerID));
            } catch (Exception ex) {
                Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_SA_updateActionPerformed

    private void btn_SA_viewhallmaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SA_viewhallmaintenanceActionPerformed
     
        try {
            managerMainPage.switchToPage(new pn_SA_viewHallMaintenance(managerMainPage, ManagerID));
        } catch (Exception ex) {
            Logger.getLogger(pn_SA_assign.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_SA_viewhallmaintenanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SA_assign;
    private javax.swing.JButton btn_SA_update;
    private javax.swing.JButton btn_SA_view;
    private javax.swing.JButton btn_SA_viewhallmaintenance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_SA_content3;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JPanel pn_SA_home;
    private javax.swing.JTable tbl_SA_schedulerassignment;
    private javax.swing.JTextField txt_SA_searchIssueID;
    // End of variables declaration//GEN-END:variables
}
