/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager;

import Class_File.FILE_IO;
import Class_File.HallClass;
import Class_File.HandleCustomerFeedback;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class View_Customer_Feedback extends javax.swing.JPanel {

    /**
     * Creates new form View_Customer_Feedback
     */
    public View_Customer_Feedback() throws Exception {
        initComponents();
        FILE_IO F = new FILE_IO();
        
        List<HandleCustomerFeedback> Feedbacks = F.getAllFeedback();
        
        DefaultTableModel model_Feedback = (DefaultTableModel) tbl_VCF_feedback.getModel();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        // 清空现有行
        model_Feedback.setRowCount(0);

        // 将每个 Hall 数据添加到表格中
        for (HandleCustomerFeedback Feedback : Feedbacks) {
            Object[] rowData = {
                Feedback.getTitle(),
                Feedback.getContent(),
                Feedback.getIssue_hall().getHall_ID(),
                Feedback.getFeedbackDateTime().format(formatter)
            };
            model_Feedback.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        pn_VCF_content = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_VCF_feedback = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        main_Panel.setLayout(new java.awt.CardLayout());

        lbl_Title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title1.setText("View Customer Feedback");

        tbl_VCF_feedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tittle", "Content", "Hall ID", "Feedback Time"
            }
        ));
        jScrollPane1.setViewportView(tbl_VCF_feedback);

        javax.swing.GroupLayout pn_VCF_contentLayout = new javax.swing.GroupLayout(pn_VCF_content);
        pn_VCF_content.setLayout(pn_VCF_contentLayout);
        pn_VCF_contentLayout.setHorizontalGroup(
            pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                        .addComponent(lbl_Title1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_VCF_contentLayout.setVerticalGroup(
            pn_VCF_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_VCF_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        main_Panel.add(pn_VCF_content, "card2");

        add(main_Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel pn_VCF_content;
    private javax.swing.JTable tbl_VCF_feedback;
    // End of variables declaration//GEN-END:variables
}
